# Generated by Django 2.2.5 on 2019-09-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_talao', models.IntegerField()),
                ('data_talao', models.DateField(auto_now=True)),
                ('hora_chamada_talao', models.TimeField(auto_now=True)),
                ('solicitante_talao', models.CharField(max_length=30)),
                ('tel_talao', models.IntegerField()),
                ('endereco_talao', models.CharField(max_length=150)),
                ('num_end_talao', models.IntegerField()),
                ('bairro_talao', models.CharField(max_length=50)),
                ('atendente_talao', models.CharField(max_length=30)),
                ('tipo_ocor_talao', models.CharField(max_length=60)),
                ('cod_talao', models.CharField(max_length=4)),
                ('viatura_talao', models.CharField(max_length=7)),
                ('hs_talao', models.TimeField()),
                ('os_talao', models.IntegerField()),
                ('hl_talao', models.TimeField()),
                ('ol_talao', models.IntegerField()),
                ('sl_talao', models.TimeField()),
                ('ps_talao', models.TimeField()),
                ('sps_talao', models.TimeField()),
                ('hpb_talao', models.TimeField()),
                ('opb_talao', models.IntegerField()),
                ('num_vit_talao', models.IntegerField()),
                ('qru_talao', models.CharField(max_length=50)),
                ('motorista_talao', models.CharField(max_length=50)),
                ('comandante_talao', models.CharField(max_length=50)),
            ],
        ),
    ]
