# Generated by Django 2.2.5 on 2019-10-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bombeiros', '0004_auto_20191002_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talao',
            name='data_talao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='talao',
            name='hora_chamada_talao',
            field=models.TimeField(),
        ),
    ]
