# Generated by Django 2.2.4 on 2019-09-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bombeiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_crm', models.IntegerField()),
                ('nome_medico_crm', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Efetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_efetivo', models.IntegerField()),
                ('post_grad_efetivo', models.CharField(max_length=5)),
                ('nome_efetivo', models.CharField(max_length=50)),
                ('nome_guerra_efetivo', models.CharField(max_length=50)),
                ('data_admissao_efetivo', models.DateField()),
                ('fone_efetivo', models.IntegerField()),
                ('cel_efetivo', models.IntegerField()),
                ('data_nasc_efetivo', models.DateField()),
                ('email_efetivo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo_viatura', models.CharField(max_length=7)),
                ('marca_modelo_viatura', models.CharField(max_length=50)),
                ('placa_viatura', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='talao',
            name='data_talao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='talao',
            name='hora_chamada_talao',
            field=models.TimeField(),
        ),
    ]
